import hall1 from "./hall1.png";
import hall2 from "./hall2.png";
import hall3 from "./hall3.png";
import hall4 from "./hall4.png";
import hall5 from "./hall5.png";
export const hall = [
  {
    id: 0,
    descript: `Lorem ipsum dolor, sit amet consectetur adipisicing el Exercitationem sunt ad enim nam corrupti natus molestiae autemperspiciatis necessitatibus temporibus delectus, quia expedita,obcaecati harum a laborum dolorem quae facere quis consequatur
          accusamus! Quidem!`,
    pool: true,
    aircon: true,
    dryer: true,
    wifi: true,
    hotTub: true,
    washer: true,
    price: "2,445",
    images: [hall1, hall2, hall3, hall4, hall5],
    numberInRoom: 4,
    numberLeft: "Four",
    star: 4.5,
    hall: hall1,
    name: "Abuta",
    location: "Legon, Accra",
  },
  {
    id: 1,
    descript: `Lorem ipsum dolor, sit amet consectetur adipisicing el Exercitationem sunt ad enim nam corrupti natus molestiae autemperspiciatis necessitatibus temporibus delectus, quia expedita,obcaecati harum a laborum dolorem quae facere quis consequatur
          accusamus! Quidem!`,
    pool: true,
    aircon: true,
    dryer: true,
    wifi: true,
    hotTub: false,
    washer: false,
    price: "4,565",
    images: [hall3, hall4, hall5],
    numberInRoom: 1,
    numberLeft: "One",
    star: 3.8,
    hall: hall2,
    name: "Madina",
    location: "Legon, Accra",
  },
  {
    id: 2,
    descript: `Lorem ipsum dolor, sit amet consectetur adipisicing el Exercitationem sunt ad enim nam corrupti natus molestiae autemperspiciatis necessitatibus temporibus delectus, quia expedita,obcaecati harum a laborum dolorem quae facere quis consequatur
          accusamus! Quidem!`,
    pool: false,
    aircon: false,
    dryer: true,
    wifi: false,
    hotTub: false,
    washer: true,
    price: "2,545",
    images: [hall1, hall2, hall3],
    numberInRoom: 4,
    numberLeft: "Three",
    star: 4.2,
    hall: hall3,
    name: "Okponglo",
    location: "Legon, Accra",
  },
  {
    id: 3,
    descript: `Lorem ipsum dolor, sit amet consectetur adipisicing el Exercitationem sunt ad enim nam corrupti natus molestiae autemperspiciatis necessitatibus temporibus delectus, quia expedita,obcaecati harum a laborum dolorem quae facere quis consequatur
          accusamus! Quidem!`,
    pool: true,
    aircon: true,
    dryer: true,
    wifi: false,
    hotTub: false,
    washer: false,
    price: "2,945",
    images: [hall1, hall4, hall5],
    numberInRoom: 3,
    numberLeft: "Two",
    star: 4.5,
    hall: hall5,
    name: "Heavens",
    location: "Obuasi, Kumasi",
  },
  {
    id: 4,
    descript: `Lorem ipsum dolor, sit amet consectetur adipisicing el Exercitationem sunt ad enim nam corrupti natus molestiae autemperspiciatis necessitatibus temporibus delectus, quia expedita,obcaecati harum a laborum dolorem quae facere quis consequatur
          accusamus! Quidem!`,
    pool: false,
    aircon: false,
    dryer: true,
    wifi: true,
    hotTub: false,
    washer: false,
    price: "1,445",
    images: [hall1, hall2],
    numberInRoom: 2,
    numberLeft: "One",
    star: 4.1,
    hall: hall4,
    name: "By Stand",
    location: "Osei-Krom, Kumasi",
  },
];
